package sherpa

import (
	"path/filepath"
	"testing"
)

func TestGeneratedGoFileSummariesDetectStandardHeader(t *testing.T) {
	root := t.TempDir()
	writeScanTestFile(t, filepath.Join(root, "generated.go"), `// Copyright test
// Code generated by gosherpa test. DO NOT EDIT.

package app

const Value = 1
`)
	writeScanTestFile(t, filepath.Join(root, "manual.go"), `// Code generated adjacent words are not enough.

package app
`)
	writeScanTestFile(t, filepath.Join(root, "raw_string.go"), "package app\n\nconst Marker = `// Code generated by a fixture. DO NOT EDIT.`\n")

	summaries := GeneratedGoFileSummaries(root, []string{
		filepath.Join(root, "manual.go"),
		filepath.Join(root, "generated.go"),
		filepath.Join(root, "raw_string.go"),
	})
	if len(summaries) != 1 {
		t.Fatalf("expected one generated summary, got %#v", summaries)
	}
	if summaries[0].Path != "generated.go" || summaries[0].Package != "." || summaries[0].PackageName != "app" {
		t.Fatalf("unexpected generated summary: %#v", summaries[0])
	}
	if summaries[0].SizeBytes == 0 {
		t.Fatalf("expected generated file size, got %#v", summaries[0])
	}
}

func TestMajorGeneratedGoPackagesAreDeterministicAndBounded(t *testing.T) {
	root := t.TempDir()
	writeGeneratedPackageTestFile(t, filepath.Join(root, "small", "a.go"), "small", "A")
	writeGeneratedPackageTestFile(t, filepath.Join(root, "large", "a.go"), "large", "A")
	writeGeneratedPackageTestFile(t, filepath.Join(root, "large", "b.go"), "large", "B")
	writeGeneratedPackageTestFile(t, filepath.Join(root, "large", "c.go"), "large", "C")

	files := []string{
		filepath.Join(root, "small", "a.go"),
		filepath.Join(root, "large", "c.go"),
		filepath.Join(root, "large", "a.go"),
		filepath.Join(root, "large", "b.go"),
	}

	packages := MajorGeneratedGoPackages(root, files, 1)
	if len(packages) != 1 {
		t.Fatalf("expected one bounded generated package, got %#v", packages)
	}
	if packages[0].Package != "large" || packages[0].PackageName != "large" || packages[0].Files != 3 {
		t.Fatalf("expected large package to be first, got %#v", packages[0])
	}
	if packages[0].LargestFile == "" || packages[0].LargestFileSizeBytes == 0 {
		t.Fatalf("expected largest file evidence, got %#v", packages[0])
	}
}

func writeGeneratedPackageTestFile(t *testing.T, path string, packageName string, symbol string) {
	t.Helper()
	writeScanTestFile(t, path, `// Code generated by gosherpa test. DO NOT EDIT.

package `+packageName+`

const Generated`+symbol+` = "`+symbol+`"
`)
}
