package sherpa

import (
	"path/filepath"
	"strings"
	"testing"
)

func TestAnalyzeRepositoryLayoutSingleModule(t *testing.T) {
	root := t.TempDir()
	writeFile(t, filepath.Join(root, "go.mod"), "module example.com/app\n\ngo 1.24.4\n")
	writeFile(t, filepath.Join(root, "service.go"), "package app\n")
	writeFile(t, filepath.Join(root, "service_test.go"), "package app\n")
	writeFile(t, filepath.Join(root, "generated.go"), "// Code generated by test. DO NOT EDIT.\npackage app\n")

	layout, warnings := AnalyzeRepositoryLayout(root)
	if len(warnings) != 0 {
		t.Fatalf("expected no layout warnings, got %v", warnings)
	}
	if layout.AnalysisBoundary != "module" {
		t.Fatalf("expected module boundary, got %s", layout.AnalysisBoundary)
	}
	if layout.ModulePath != "example.com/app" {
		t.Fatalf("expected module path, got %s", layout.ModulePath)
	}
	if layout.GoModPath != "go.mod" {
		t.Fatalf("expected go.mod path, got %s", layout.GoModPath)
	}
	if layout.GoFiles != 3 || layout.TestFiles != 1 || layout.GeneratedFiles != 1 {
		t.Fatalf("unexpected file counts: %#v", layout)
	}
	if len(layout.GeneratedPackages) != 1 || layout.GeneratedPackages[0].Package != "." || layout.GeneratedPackages[0].PackageName != "app" {
		t.Fatalf("unexpected generated package summary: %#v", layout.GeneratedPackages)
	}
	if layout.WorkspaceModules == nil || layout.LocalReplacements == nil || layout.SkippedNestedModules == nil {
		t.Fatalf("expected non-nil layout arrays: %#v", layout)
	}
}

func TestAnalyzeRepositoryLayoutReportsWorkspaceBoundary(t *testing.T) {
	root := t.TempDir()
	external := filepath.Join(filepath.Dir(root), "external")
	writeFile(t, filepath.Join(root, "go.work"), "go 1.24.4\n\nuse (\n\t./app\n\t./service\n\t../external\n)\n")
	writeFile(t, filepath.Join(root, "app", "go.mod"), "module example.com/app\n\ngo 1.24.4\n")
	writeFile(t, filepath.Join(root, "app", "app.go"), "package app\n")
	writeFile(t, filepath.Join(root, "service", "go.mod"), "module example.com/service\n\ngo 1.24.4\n")
	writeFile(t, filepath.Join(root, "service", "service.go"), "package service\n")
	writeFile(t, filepath.Join(external, "go.mod"), "module example.com/external\n\ngo 1.24.4\n")

	layout, warnings := AnalyzeRepositoryLayout(root)
	if layout.AnalysisBoundary != "workspace" {
		t.Fatalf("expected workspace boundary, got %s", layout.AnalysisBoundary)
	}
	if !layout.GoWork.Detected || layout.GoWork.Path != "go.work" || layout.GoWork.Scope != "root" {
		t.Fatalf("unexpected go.work summary: %#v", layout.GoWork)
	}
	if len(layout.WorkspaceModules) != 3 {
		t.Fatalf("expected 3 workspace modules, got %#v", layout.WorkspaceModules)
	}
	if !layoutHasWorkspaceModule(layout, "app", true, true) || !layoutHasWorkspaceModule(layout, "service", true, true) {
		t.Fatalf("expected included workspace modules, got %#v", layout.WorkspaceModules)
	}
	if len(layout.SkippedWorkspaceModules) != 1 || !strings.Contains(layout.SkippedWorkspaceModules[0], "external") {
		t.Fatalf("expected skipped external workspace module, got %#v", layout.SkippedWorkspaceModules)
	}
	if len(layout.SkippedNestedModules) != 0 {
		t.Fatalf("workspace modules inside root should not be skipped nested modules, got %#v", layout.SkippedNestedModules)
	}
	if !strings.Contains(strings.Join(warnings, "\n"), "workspace modules outside the selected root") {
		t.Fatalf("expected external workspace warning, got %v", warnings)
	}
}

func TestAnalyzeRepositoryLayoutReportsSkippedNestedModules(t *testing.T) {
	root := t.TempDir()
	writeFile(t, filepath.Join(root, "go.mod"), "module example.com/root\n\ngo 1.24.4\n")
	writeFile(t, filepath.Join(root, "root.go"), "package root\n")
	writeFile(t, filepath.Join(root, "nested", "go.mod"), "module example.com/nested\n\ngo 1.24.4\n")
	writeFile(t, filepath.Join(root, "nested", "nested.go"), "package nested\n")

	layout, warnings := AnalyzeRepositoryLayout(root)
	if len(layout.NestedModules) != 1 || layout.NestedModules[0] != "nested" {
		t.Fatalf("expected nested module, got %#v", layout.NestedModules)
	}
	if len(layout.SkippedNestedModules) != 1 || layout.SkippedNestedModules[0] != "nested" {
		t.Fatalf("expected skipped nested module, got %#v", layout.SkippedNestedModules)
	}
	if !strings.Contains(strings.Join(warnings, "\n"), "inspect them with --root <path>") {
		t.Fatalf("expected --root inspection warning, got %v", warnings)
	}
}

func TestAnalyzeRepositoryLayoutReportsLocalReplacements(t *testing.T) {
	root := t.TempDir()
	writeFile(t, filepath.Join(root, "go.mod"), `module example.com/root

go 1.24.4

require example.com/lib v0.0.0

replace example.com/lib => ./lib
`)
	writeFile(t, filepath.Join(root, "root.go"), `package root

import "example.com/lib"

var _ = lib.Value
`)
	writeFile(t, filepath.Join(root, "lib", "go.mod"), "module example.com/lib\n\ngo 1.24.4\n")
	writeFile(t, filepath.Join(root, "lib", "lib.go"), "package lib\n\nconst Value = 1\n")

	layout, warnings := AnalyzeRepositoryLayout(root)
	if len(layout.LocalReplacements) != 1 {
		t.Fatalf("expected local replacement, got %#v", layout.LocalReplacements)
	}
	replacement := layout.LocalReplacements[0]
	if replacement.ModulePath != "example.com/lib" || replacement.Path != "lib" || !replacement.InsideRoot {
		t.Fatalf("unexpected replacement summary: %#v", replacement)
	}
	if len(layout.SkippedNestedModules) != 1 || layout.SkippedNestedModules[0] != "lib" {
		t.Fatalf("expected replaced nested module to stay outside root analysis, got %#v", layout.SkippedNestedModules)
	}
	if !strings.Contains(strings.Join(warnings, "\n"), "nested modules skipped") {
		t.Fatalf("expected nested module warning, got %v", warnings)
	}
}

func layoutHasWorkspaceModule(layout RepositoryLayout, path string, insideRoot bool, included bool) bool {
	for _, module := range layout.WorkspaceModules {
		if module.Path == path && module.InsideRoot == insideRoot && module.Included == included {
			return true
		}
	}
	return false
}
